version: "3.9"

services:
  e-server:
    image: e-server
    container_name: e-serverContainer
    hostname: e-server
    build:
      context: ./e_server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - usermanagement

  apigateway:
    image: apigateway
    container_name: apigatewayContainer
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    depends_on:
      - e-server
    ports:
      - "8080:8080"
    networks:
      - usermanagement
  user-service:
    image: user-service
    container_name: user-serviceContainer
    build:
      context: ./user_service
      dockerfile: Dockerfile
    depends_on:
      - apigateway
    ports:
      - "9001:9001"
    networks:
      - usermanagement

  contact-service:
    image: contact-service
    container_name: contact-serviceContainer
    build:
      context: ./contact_service
      dockerfile: Dockerfile
    depends_on:
      - apigateway
    ports:
      - "9002:9002"
    networks:
      - usermanagement

networks:
  usermanagement:
