apiVersion: v1
kind: Service
metadata:
  name: contact-service
  labels:
    app: contact-service
spec:
  type: NodePort    #NodePort   #
  selector:
    app: contact-service
  ports:
    - protocol: "TCP"
      port: 9002
      targetPort: 9002
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-service # name of micro-service
spec:
  selector:
    matchLabels:
      app: contact-service
  replicas: 1         # how many pods you run
  template:
    metadata:
      labels:
        app: contact-service
    spec:
      containers:
        - name: contact-service
          image: contact-service
          imagePullPolicy: Never
          ports:
            - containerPort: 9002
        #   initContainers:
      #  - name: gateway-service