spring:
  application:
    name: contact-service
  profiles:
    active: dev

server:
  port: 9002

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/