spring:
  application:
    name: contact-service
  profile:
    active: docker

server:
  port: 9002

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://e-server:8761/eureka/